/* tslint:disable */
/* eslint-disable */
/**
 * School API
 * School API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: orscarsilla@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SectionResponse
 */
export interface SectionResponse {
    /**
     * 
     * @type {string}
     * @memberof SectionResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SectionResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SectionResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SectionResponse
     */
    img?: string;
    /**
     * 
     * @type {string}
     * @memberof SectionResponse
     */
    ref?: string;
}

/**
 * Check if a given object implements the SectionResponse interface.
 */
export function instanceOfSectionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SectionResponseFromJSON(json: any): SectionResponse {
    return SectionResponseFromJSONTyped(json, false);
}

export function SectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '_id') ? undefined : json['_id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'img': !exists(json, 'img') ? undefined : json['img'],
        'ref': !exists(json, 'ref') ? undefined : json['ref'],
    };
}

export function SectionResponseToJSON(value?: SectionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': value.id,
        'title': value.title,
        'description': value.description,
        'img': value.img,
        'ref': value.ref,
    };
}

