/* tslint:disable */
/* eslint-disable */
/**
 * School API
 * School API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: orscarsilla@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SectionBody
 */
export interface SectionBody {
    /**
     * 
     * @type {string}
     * @memberof SectionBody
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SectionBody
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof SectionBody
     */
    img?: string;
}

/**
 * Check if a given object implements the SectionBody interface.
 */
export function instanceOfSectionBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function SectionBodyFromJSON(json: any): SectionBody {
    return SectionBodyFromJSONTyped(json, false);
}

export function SectionBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'img': !exists(json, 'img') ? undefined : json['img'],
    };
}

export function SectionBodyToJSON(value?: SectionBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'img': value.img,
    };
}

