/* tslint:disable */
/* eslint-disable */
/**
 * School API
 * School API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: orscarsilla@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoRequest
 */
export interface VideoRequest {
    /**
     * 
     * @type {string}
     * @memberof VideoRequest
     */
    ref: string;
    /**
     * 
     * @type {string}
     * @memberof VideoRequest
     */
    src: string;
}

/**
 * Check if a given object implements the VideoRequest interface.
 */
export function instanceOfVideoRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ref" in value;
    isInstance = isInstance && "src" in value;

    return isInstance;
}

export function VideoRequestFromJSON(json: any): VideoRequest {
    return VideoRequestFromJSONTyped(json, false);
}

export function VideoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ref': json['ref'],
        'src': json['src'],
    };
}

export function VideoRequestToJSON(value?: VideoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ref': value.ref,
        'src': value.src,
    };
}

