/* tslint:disable */
/* eslint-disable */
/**
 * School API
 * School API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: orscarsilla@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoSourceRequest
 */
export interface VideoSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof VideoSourceRequest
     */
    src: string;
}

/**
 * Check if a given object implements the VideoSourceRequest interface.
 */
export function instanceOfVideoSourceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "src" in value;

    return isInstance;
}

export function VideoSourceRequestFromJSON(json: any): VideoSourceRequest {
    return VideoSourceRequestFromJSONTyped(json, false);
}

export function VideoSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoSourceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'src': json['src'],
    };
}

export function VideoSourceRequestToJSON(value?: VideoSourceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'src': value.src,
    };
}

