/* tslint:disable */
/* eslint-disable */
/**
 * School API
 * School API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: orscarsilla@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoType
 */
export interface VideoType {
    /**
     * 
     * @type {string}
     * @memberof VideoType
     */
    ref?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoType
     */
    src?: string;
}

/**
 * Check if a given object implements the VideoType interface.
 */
export function instanceOfVideoType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VideoTypeFromJSON(json: any): VideoType {
    return VideoTypeFromJSONTyped(json, false);
}

export function VideoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ref': !exists(json, 'ref') ? undefined : json['ref'],
        'src': !exists(json, 'src') ? undefined : json['src'],
    };
}

export function VideoTypeToJSON(value?: VideoType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ref': value.ref,
        'src': value.src,
    };
}

