/* tslint:disable */
/* eslint-disable */
/**
 * School API
 * School API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: orscarsilla@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoSourceType
 */
export interface VideoSourceType {
    /**
     * 
     * @type {string}
     * @memberof VideoSourceType
     */
    src?: string;
}

/**
 * Check if a given object implements the VideoSourceType interface.
 */
export function instanceOfVideoSourceType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VideoSourceTypeFromJSON(json: any): VideoSourceType {
    return VideoSourceTypeFromJSONTyped(json, false);
}

export function VideoSourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoSourceType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'src': !exists(json, 'src') ? undefined : json['src'],
    };
}

export function VideoSourceTypeToJSON(value?: VideoSourceType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'src': value.src,
    };
}

