swagger: "2.0"
info:
  title: School API
  description: School API
  version: 1.0.1
  contact:
    email: orscarsilla@outlook.com
tags:
  - name: video
    description: Manage videos from school web page
  - name: section
    description: Manage sections from school web page
consumes:
  - application/json
produces:
  - application/json
paths:
  /video:
    post:
      tags:
        - "video"
      summary: "Create video"
      description: "Create video"
      operationId: "createVideo"
      parameters:
        - $ref: "#/parameters/videoBodyParam"
      responses:
        '201':
          description: Created successfully.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /video/{id}:
    get:
      tags:
        - "video"
      summary: "Get an existing video"
      description: "Get existing video by ObjectId."
      operationId: "getVideo"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/VideoResponse'
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      tags:
        - "video"
      summary: "Modify an existing video"
      description: "Modify 'src' from video."
      operationId: "modifyVideo"
      parameters:
        - $ref: "#/parameters/idParam"
        - $ref: "#/parameters/videoSourceBodyParam"
      responses:
        '200':
          description: OK.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sections:
    post:
      tags:
        - "section"
      summary: "Create section"
      description: "Create section"
      operationId: "createSection"
      parameters:
        - $ref: "#/parameters/sectionBodyParam"
      responses:
        '201':
          description: Created successfully.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - "section"
      summary: "Get sections"
      description: "Get all sections"
      operationId: "getSections"
      responses:
        '200':
          description: OK.
          schema:
            $ref: "#/definitions/SectionsResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sections/{id}:
    get:
      tags:
        - "section"
      summary: "Get an existing section"
      description: "Get an existing section by ObjectId."
      operationId: "getSection"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/SectionResponse'
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      tags:
        - "section"
      summary: "Modify an existing section"
      description: "Modify an existing section by ObjectId"
      operationId: "modifySection"
      parameters:
        - $ref: "#/parameters/idParam"
        - $ref: "#/parameters/sectionBodyParam"
      responses:
        '200':
          description: OK.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - "section"
      summary: "Delete an existing section"
      description: "Delete an existing section by ObjectId"
      operationId: "deleteSection"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '204':
          description: No content.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  VideoResponse:
    type: object
    required:
      - "_id"
      - "ref"
      - "src"
    properties:
      _id:
        type: string
        format: string
        example: "507f191e810c19729de860ea"
      ref:
        type: string
        format: string
        example: home
      src:
        type: string
        format: string
        example: <iframe width="560" height="315" src="https://www.youtube.com/embed/d6q8T2jfjm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  ErrorResponse:
    type: object
    required:
      - "code"
      - "description"
    properties:
      code:
        type: integer
        format: int32
      description:
        type: string
        format: string
  VideoRequest:
    type: object
    required:
      - "ref"
      - "src"
    properties:
      ref:
        type: string
        format: string
        example: home
      src:
        type: string
        format: string
        example: <iframe width="560" height="315" src="https://www.youtube.com/embed/d6q8T2jfjm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  VideoSourceRequest:
    type: object
    required:
      - "src"
    properties:
      src:
        type: string
        format: string
        example: <iframe width="560" height="315" src="https://www.youtube.com/embed/d6q8T2jfjm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  SectionBody:
    type: object
    required:
      - "title"
    properties:
      title:
        type: string
        format: string
        example: "Educational Principles"
      description:
        type: string
        format: string
        example: "Educational principles are the core of the school."
      img:
        type: string
        format: string
        example: "example.png"
  SectionsResponse:
    type: array
    items:
      $ref: "#/definitions/SectionResponse"
  SectionResponse:
    type: object
    properties:
      _id:
        type: string
        format: string
        example: "507f191e810c19729de860ea"
      title:
        type: string
        format: string
        example: "Educational Principles"
      description:
        type: string
        format: string
        example: "Educational principles are the core of the school."
      img:
        type: string
        format: string
        example: "example.png"
      ref:
        type: string
        format: string
        example: "educational_principles"
parameters:
  idParam:
    name: "_id"
    description: "ObjectId param."
    in: path
    required: true
    type: string
    format: string
  videoBodyParam:
    name: "body"
    description: "Video body"
    in: body
    required: true
    schema:
      $ref: "#/definitions/VideoRequest"
  videoSourceBodyParam:
    name: "body"
    description: "Video source body param."
    in: body
    required: true
    schema:
      $ref: "#/definitions/VideoSourceRequest"
  sectionBodyParam:
    name: "body"
    description: "Section body"
    in: body
    required: true
    schema:
      $ref: "#/definitions/SectionBody"

