swagger: "2.0"
info:
  title: School API
  description: School API
  version: 1.0.4
  contact:
    email: orscarsilla@outlook.com
tags:
  - name: video
    description: Manage videos from school web page
  - name: section
    description: Manage sections from school web page
  - name: users
    description: Manage users from school web page
  - name: login
    description: Manage login from school web page
  - name: stories
    description: Manage stories from school web page
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    post:
      tags:
        - "users"
      summary: "Create user"
      description: "Create a new user (Register)"
      operationId: "createUser"
      parameters:
        - $ref: "#/parameters/userBodyParam"
      responses:
        '201':
          description: Created successfully.
          schema:
            $ref: "#/definitions/GeneratedIdResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - "users"
      summary: "Get all users"
      description: "Get all users"
      operationId: "getUsers"
      responses:
        '200':
          description: Ok.
          schema:
            $ref: "#/definitions/UsersResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}:
    get:
      tags:
        - "users"
      summary: "Get user"
      description: "Get one user by _id"
      operationId: "getUser"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '200':
          description: Ok.
          schema:
            $ref: "#/definitions/UserResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - "users"
      summary: "Delete user"
      description: "Delete user by id"
      operationId: "deleteUser"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '204':
          description: No Content.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /video:
    post:
      tags:
        - "video"
      summary: "Create video"
      description: "Create video"
      operationId: "createVideo"
      parameters:
        - $ref: "#/parameters/videoBodyParam"
      responses:
        '201':
          description: Created successfully.
          schema:
            $ref: "#/definitions/GeneratedIdResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /video/{id}:
    patch:
      tags:
        - "video"
      summary: "Modify an existing video"
      description: "Modify 'src' from video."
      operationId: "modifyVideo"
      parameters:
        - $ref: "#/parameters/idParam"
        - $ref: "#/parameters/videoSourceBodyParam"
      responses:
        '200':
          description: OK.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - "video"
      summary: "Delete video"
      description: "Delete video by id"
      operationId: "deleteVideo"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '204':
          description: No content.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /video/{ref}:
    get:
      tags:
        - "video"
      summary: "Get an existing video"
      description: "Get existing video by ObjectId."
      operationId: "getVideo"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/VideoResponse'
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sections:
    post:
      tags:
        - "section"
      summary: "Create section"
      description: "Create section"
      operationId: "createSection"
      parameters:
        - $ref: "#/parameters/sectionBodyParam"
      responses:
        '201':
          description: Created successfully.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - "section"
      summary: "Get sections"
      description: "Get all sections"
      operationId: "getSections"
      responses:
        '200':
          description: OK.
          schema:
            $ref: "#/definitions/SectionsResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sections/{ref}:
    get:
      tags:
        - "section"
      summary: "Get an existing section"
      description: "Get an existing section by ObjectId."
      operationId: "getSection"
      parameters:
        - $ref: "#/parameters/sectionReference"
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/SectionResponse'
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      tags:
        - "section"
      summary: "Modify an existing section"
      description: "Modify an existing section by ObjectId"
      operationId: "modifySection"
      parameters:
        - $ref: "#/parameters/sectionReference"
        - $ref: "#/parameters/sectionBodyParam"
      responses:
        '200':
          description: OK.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - "section"
      summary: "Delete an existing section"
      description: "Delete an existing section by ObjectId"
      operationId: "deleteSection"
      parameters:
        - $ref: "#/parameters/sectionReference"
      responses:
        '204':
          description: No content.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
    post:
      tags:
        - "login"
      summary: "Login"
      description: "Login"
      operationId: "login"
      parameters:
        - $ref: "#/parameters/loginParam"
      responses:
        '200':
          description: OK.
          schema:
            $ref: "#/definitions/LoginResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /stories:
    get:
      tags:
        - "stories"
      summary: "Get stories"
      description: "Get all stories"
      operationId: "getStories"
      responses:
        '200':
          description: OK.
          schema:
            $ref: "#/definitions/StoriesResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - "stories"
      summary: "Create new"
      description: "Create new"
      operationId: "createStory"
      parameters:
        - $ref: "#/parameters/newBodyParam"
      responses:
        '201':
          description: Created.
          schema:
            $ref: "#/definitions/GeneratedIdResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
  /stories/{id}:
    get:
      tags:
        - "stories"
      summary: "Get new"
      description: "Get new by id"
      operationId: "getStory"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '200':
          description: OK.
          schema:
            $ref: "#/definitions/StoryResponse"
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags:
        - "stories"
      summary: "Update new"
      description: "Update new by id"
      operationId: "updateStory"
      parameters:
        - $ref: "#/parameters/idParam"
        - $ref: "#/parameters/newBodyParam"
      responses:
        '200':
          description: OK.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - "stories"
      summary: "Delete new"
      description: "Delete new by id"
      operationId: "deleteStory"
      parameters:
        - $ref: "#/parameters/idParam"
      responses:
        '204':
          description: No content.
        '400':
          description: Bad request.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '401':
          description: Unauthorized.
          schema:
            $ref: "#/definitions/ErrorResponse"
        '404':
          description: Not found.
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  StoryBody:
    type: object
    required:
      - "title"
      - "content"
    properties:
      title:
        type: string
        format: string
        example: "First new"
      description:
        type: string
        format: string
        example: "Storie description"
      img:
        type: string
        format: string
        example: "portrait.jpg"
      content:
        type: string
        format: string
        example: "<h1>Content</h1>"
  StoriesResponse:
    type: array
    items:
      $ref: "#/definitions/StoryResponse"
  StoryResponse:
    type: object
    required:
      - "_id"
      - "title"
      - "content"
    properties:
      _id:
        type: string
        format: string
        example: "507f191e810c19729de860ea"
      title:
        type: string
        format: string
        example: "First new"
      description:
        type: string
        format: string
        example: "Storie description"
      img:
        type: string
        format: string
        example: "portrait.jpg"
      content:
        type: string
        format: string
        example: "<h1>Content</h1>"
  VideoResponse:
    type: object
    required:
      - "_id"
      - "ref"
      - "src"
    properties:
      _id:
        type: string
        format: string
        example: "507f191e810c19729de860ea"
      ref:
        type: string
        format: string
        example: home
      src:
        type: string
        format: string
        example: <iframe width="560" height="315" src="https://www.youtube.com/embed/d6q8T2jfjm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  ErrorResponse:
    type: object
    required:
      - "code"
      - "description"
    properties:
      code:
        type: integer
        format: int32
      description:
        type: string
        format: string
  VideoBody:
    type: object
    required:
      - "ref"
      - "src"
    properties:
      ref:
        type: string
        format: string
        example: home
      src:
        type: string
        format: string
        example: <iframe width="560" height="315" src="https://www.youtube.com/embed/d6q8T2jfjm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  VideoSourceBody:
    type: object
    required:
      - "src"
    properties:
      src:
        type: string
        format: string
        example: <iframe width="560" height="315" src="https://www.youtube.com/embed/d6q8T2jfjm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  SectionBody:
    type: object
    required:
      - "title"
    properties:
      title:
        type: string
        format: string
        example: "Educational Principles"
      description:
        type: string
        format: string
        example: "Educational principles are the core of the school."
      img:
        type: string
        format: string
        example: "example.png"
  UserBody:
    type: object
    required:
      - "username"
      - "password"
      - "name"
      - "email"
    properties:
      username:
        type: string
        format: string
        example: "osilla"
      password:
        type: string
        format: string
        example: "1234"
      name:
        type: string
        format: string
        example: "Don Quijote"
      email:
        type: string
        format: string
        example: "oscarsilla@outlook.com"
      surnames:
        type: string
        format: string
        example: "De la mancha"
      avatar:
        type: string
        format: string
        example: "avatar.png"
  LoginBody:
    type: object
    required:
      - "email"
      - "password"
    properties:
      email:
        type: string
        format: string
        example: "osilla@outlook.com"
      password:
        type: string
        format: string
        example: "1234"
  LoginResponse:
    type: object
    required:
      - "token"
    properties:
      token:
        type: string
        format: string
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
  SectionsResponse:
    type: array
    items:
      $ref: "#/definitions/SectionResponse"
  SectionResponse:
    type: object
    properties:
      _id:
        type: string
        format: string
        example: "507f191e810c19729de860ea"
      title:
        type: string
        format: string
        example: "Educational Principles"
      description:
        type: string
        format: string
        example: "Educational principles are the core of the school."
      img:
        type: string
        format: string
        example: "example.png"
      ref:
        type: string
        format: string
        example: "educational_principles"
  UsersResponse:
    type: array
    items:
      $ref: "#/definitions/UserResponse"
  UserResponse:
    type: object
    properties:
      _id:
        type: string
        format: string
        example: 507f191e810c19729de860ea
      username:
        type: string
        format: string
        example: "osilla"
      password:
        type: string
        format: string
        example: "1234"
      name:
        type: string
        format: string
        example: "Don Quijote"
      email:
        type: string
        format: string
        example: "oscarsilla@outlook.com"
      surnames:
        type: string
        format: string
        example: "De la mancha"
      avatar:
        type: string
        format: string
        example: "avatar.png"
  GeneratedIdResponse:
    type: object
    properties:
      generatedId:
        type: string
        format: string
        example: "63b04cf26cff5203de1659ca"
parameters:
  idParam:
    name: "_id"
    description: "ObjectId param."
    in: path
    required: true
    type: string
    format: string
  sectionReference:
    name: "ref"
    description: "Section reference filter to find, update and delete a section."
    in: path
    required: true
    type: string
    format: string
  videoBodyParam:
    name: "body"
    description: "Video body"
    in: body
    required: true
    schema:
      $ref: "#/definitions/VideoBody"
  videoSourceBodyParam:
    name: "body"
    description: "Video source body param."
    in: body
    required: true
    schema:
      $ref: "#/definitions/VideoSourceBody"
  sectionBodyParam:
    name: "body"
    description: "Section body"
    in: body
    required: true
    schema:
      $ref: "#/definitions/SectionBody"
  userBodyParam:
    name: "body"
    description: "User body param"
    in: body
    required: true
    schema:
      $ref: "#/definitions/UserBody"
  loginParam:
    name: "body"
    description: "Login body params"
    in: body
    required: true
    schema:
      $ref: "#/definitions/LoginBody"
  newBodyParam:
    name: "body"
    description: "Storie body param"
    in: body
    required: true
    schema:
      $ref: "#/definitions/StoryBody"
